#!/usr/bin/with-contenv /bin/bash
if ([ -f /home/user/coolq/CQA.exe ] || [ -f /home/user/coolq/CQP.exe ]); then
    echo 'CoolQ already exists, skip download.'
else
    echo 'Downloading CoolQ ...'
    mkdir /tmp/cq
    wget $COOLQ_URL -O /tmp/cq/coolq.zip
    echo 'Unzipping CoolQ ...'
    cd /tmp/cq
    LC_ALL=zh_CN.UTF-8 unzip coolq.zip > /dev/null
    mv */* /home/user/coolq
    chown -R user:user /home/user/coolq
    rm -rf /tmp/cq
fi